- hosts: master
  become: yes
  tasks:
    - name: Install K3s on master node
      shell: curl -sfL https://get.k3s.io | sh -

- hosts: workers
  become: yes
  tasks:
    - name: Install K3s agent on worker nodes
      shell: curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['master'].ansible_host }}:6443 K3S_TOKEN=mytoken sh -
